microsoft/azure-pipelines-yaml

design/pipeline-artifacts.md
**(Note, below is the original PR text. For the best experience, start with "Files changed", which has the final proposal.)**
Moving this over from a private repo. Also separating out this proposal from the use/auth proposal (#40).
@ashokirla can you take a look at this and see if I've covered all your feedback? I looked at your Word doc and tried to hew as closely as possible to your `downloadArtifacts` section, but I couldn't do it 100% since you can't have a value and then a list (e.g. [1]). So, I instead propose providing the resource as a separate key (see line 43 of this file). Thoughts?
I think we're pretty close to locking this in, which means we can then schedule the work:
1. On Artifacts Core, ensuring the tasks support the options we want to expose here, and updating the tasks …
=> Pipeline Artifacts proposal

templates/go.yml
This PR is related this issue. https://developercommunity.visualstudio.com/content/problem/420440/go-template-ignore-dot-files.html
The current go template ignore the dot files. like .foo. It copys Go files however, it doesn't work if they require the dot files.
Since I'm not sure if you have some intent for not using dotglob, I just want to share the issue and hopefully contribute it.
Also related this PR.
https://github.com/MicrosoftDocs/pipelines-go/pull/5
=> fix to ignore dot files to copy

templates/docker-container-functionapp.properties.json, templates/docker-container-to-acr.properties.json, templates/docker-container-to-aks.properties.json, templates/docker-container-webapp.properties.json
Changing the templates' requires field to a list of required input objects. This will map to the TaskInputDefinition class on the server side. If you look at the actual yaml for these templates, the required inputs are serviceEndpointId and repositoryName. Basically azuresubscription (which is the current required input) is a serviceEndpointId that is of type connectedService:azureRM. On the server, azuresubscription  doesn't map to anything while the other name/type do. 
This additional information will allow us to take in these required inputs and replace them in the templates to get a complete yaml. The server side PR will be out after this one is completed.
=> Updating required inputs for templates

templates/python-django.yml
Moves the `succeededOrFailed()` condition to the correct task.
=> Fix task condition

templates/docker-container-functionapp.properties.json, templates/docker-container-to-acr.properties.json, templates/docker-container-to-aks.properties.json, templates/docker-container-webapp.properties.json
The properties.json mentions it requires a parameter called `serviceEndpointId` but the yaml uses `azureServiceConnectionId`.
This PR fixes that.
=> Fixing parameter names in properties.json files

templates/universal-windows-platform.yml
Fix the appxPackageDir variable in the UWP yaml template by adding a trailing slash
=> Fix appxPackageDir variable in UWP template

templates/deploy-to-existing-kubernetes-cluster.yml
1. Fixes a bug where deployment name cannot have spaces
2. Adds pool name to each job, as the stage schema mandates that
=> [Deploy to k8s] Fixing stage related bugs in template

templates/deploy-to-existing-kubernetes-cluster.properties.json, templates/deploy-to-existing-kubernetes-cluster.yml
Fixes a bug in the template. 
The deploy job was creating the imagePullSecret in `default` namespace when it should have been created in `$(k8sNamespace)`
Updates the title of the template from `Deploy to Kubernetes` to `Deploy to Azure Kubernetes Service (AKS)`
=> [DeployToK8s] Creating secret in correct namespace

templates/deploy-to-existing-kubernetes-cluster.properties.json, templates/deploy-to-existing-kubernetes-cluster.yml
`kubernetesConnection` is removed as a required paramter since it is no longer referred  in template
=> Fixing manifest extension to YML and removing kubernetesConnection as required parameter

templates/deploy-to-existing-kubernetes-cluster.yml, templates/docker-container.yml
1. Removed the word `job` from the display name
2. Removed `DownloadPipelineArtifact` step because the deploy job linking downloads the artifacts by default now.
=> Removing job from display name

templates/deploy-to-existing-kubernetes-cluster.yml, templates/maven-webapp-to-linux-on-azure.yml, templates/node.js-express-webapp-to-linux-on-azure.yml, templates/node.js-functionapp-to-linux-on-azure.yml, templates/node.js-react-webapp-to-linux-on-azure.yml
Update node.js and java templates:
- replace publish artifact by upload shortcut
- remove download artifact step as it is auto-injected in deployment job
- build extensions conditionally in node.js function app
=> Update node.js and java templates

templates/maven.yml
Maven3 task does not log a warning if no test results are found. There could be a slight perf impact looking for the test files but the benefit customers get via rich test result reporting we think outweighs the additional time added to the run.
=> Update maven.yml to allow publishing test results by default

templates/deploy-to-existing-kubernetes-cluster.properties.json, templates/docker-container.properties.json, templates/maven-webapp-to-linux-on-azure.properties.json, templates/node.js-express-webapp-to-linux-on-azure.properties.json, templates/node.js-functionapp-to-linux-on-azure.properties.json, templates/node.js-react-webapp-to-linux-on-azure.properties.json
These types have custom UI and so don't show these names, but the code that serves them from the backend doesn't know that and it flags them as missing names via debugger break.  This is annoying, so let's just give them some names.
=> Adding display names for parameters that are missing them

design/node10-agent-support.md
Design doc to add Node v10 support to agent tasks, in the form of a new 'Node10' handler.
PR which implements this feature: https://github.com/Microsoft/azure-pipelines-agent/pull/1972
=> Azure Pipelines agent Node V10 support design doc

design/multicheckout.md
It *appears* that `root` was inconsistently used here and that `path` was probably what was intended.
Please confirm before completing PR.
If this *was* correct before my change, there lacks any explanation or docs that I can find for what `root` means.
=> Fix checkout path name

design/multi-checkout.md
We talked about a different design for where to checkout sources. This PR reflects that discussion.
=> Propose different behavior for dealing with the `/s` directory

templates/resources/k8s/deployment.yml
Upgraded the api-version to `apps/v1` as `apps/v1beta1` got deprecated and is causing the pipeline to fail.
=> Changed api-version to v1 and added matchLabels to deployment spec

templates/python-functionapp-to-linux-on-azure.yml
Updated to use new python package location since venv is no longer supported
=> Updated to use new python package location 

design/pipeline-artifacts.md
Updates the existing design for working with pipeline artifacts. Highlights:
1. Switches back to using "publish" terminology to avoid introducing a new term and to avoid a naming misalignment between the keyword (`publish`) and its associated task (_Publish Pipeline Artifact_)
2. Clarifies behavior when different combinations of `path` and `artifact` are specified, including cases involving absolute paths
=> Design updates for Pipeline Artifacts (May 2019)

design/deployment-strategies.md, design/deployment.md
Removed blue-green strategy from docs - since it's obsolete.
Up-to-date docs - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops
=> Removed blue-green strategy from docs

design/deprecated/container-steps.md
This PR replaces the incorrect environment variable DOTNET_TELEMETRY_OPT_OUT in container-steps.md
Incorrect env var DOTNET_TELEMETRY_OPT_OUT usage in container-steps.md (supposed to be DOTNET_CLI_TELEMETRY_OPTOUT) [#564 ](https://github.com/microsoft/azure-pipelines-yaml/issues/564)
=> Fix incorrect environment variable in container-steps.md

templates/node.js-express-webapp-to-linux-on-azure.yml
Could you please update the Node.js Express template to use a newer version of Node.js? It's used in our documentation samples.
=> Update Node Express template to use 16 LTS
