microsoft/azure-pipelines-yaml

design/container-steps-implementation.md

Adding doc to master for anybody to have a reference in the future.

Adding container steps design doc spike

---

design/yaml-principles.md

Would love some public feedback on this list.

Add Principles list

---

templates/docker-container-functionapp.yml
templates/docker-container-to-acr.yml
templates/docker-container-to-aks.yml
templates/docker-container-webapp.yml

Deepak and Lova, could you please consider these changes that make the new YAML template titles/descriptions match the format of the existing built-in templates?  Thanks!

 Unify YAML template title/description format

---

templates/python-package.yml

**Testing**
Ran a build with the new YAML

Simplify Python template

---

design/checkout-path.md
design/multicheckout.md

After reviewing in-box tasks and discussion with engineering, I don't like my earlier variables proposal. This one is less likely to break any assumptions, and moves us in a better direction for the future.

design change to sources variables

---

templates/python-package.yml

The plugin automatically produces and uploads JUnit XML, among some other great things: https://pypi.org/project/pytest-azurepipelines/
Includes some other small simplifications to the template.

Use Pytest plugin for Azure Pipelines

---

templates/docker-container-functionapp.properties.json
templates/docker-container-to-acr.properties.json
templates/docker-container-to-aks.properties.json
templates/docker-container-webapp.properties.json

These parameters are going to be displayed on the UI soon, so we need human-readable names for them.

Adding display names for parameters

---

templates/docker-container-functionapp.properties.json
templates/docker-container-to-acr.properties.json
templates/docker-container-to-aks.properties.json
templates/docker-container-webapp.properties.json

Update parameter display names

---

design/environment.md

As per discussion, adding `deploy` node to align with deployment strategies

Adde `deploy` node under default strategy

---

design/pipeline-resources.md

Fixing the download task example to use the artifact keyword

fixing the download task example

---

templates/node.js-express-webapp-on-linux.properties.json
templates/node.js-express-webapp-on-linux.yml
templates/node.js-react-webapp-on-linux.properties.json
templates/node.js-react-webapp-on-linux.yml

node.js CI + CD templates for:
- Express apps targeting Linux Web App on Azure
- React apps targeting Linux Web App on Azure

Adding templates for building and deploying nodeJs express and react web apps on linux

---

templates/deploy-to-existing-kubernetes-cluster.yml

Hi @ds-ms!  The other templates standardize on using the vmImage name instead of the hosted pool name.  Would you be okay with doing the same thing here?

Use vmImage name instead of pool name

---

templates/deploy-to-existing-kubernetes-cluster.properties.json

This PR adds more properties i.e. `destinationPath` and `description` to the file assets.

[K8s] Adding more properties to assets

---

templates/deploy-to-existing-kubernetes-cluster.properties.json
templates/deploy-to-existing-kubernetes-cluster.yml

This PR removes the environment object and introduces a new object of `environmentResource:kubernetes`. This helps in being explicit about the type of objects that are being created

Modifying the template to consume information from KubernetesResource

---

templates/node.js-express-webapp-on-linux.yml
templates/node.js-functionapp-on-linux.properties.json
templates/node.js-functionapp-on-linux.yml
templates/node.js-react-webapp-on-linux.yml

- Adding template to build and deploy node.js function app on Linux.
- Node.js Express web app - separate stages for Build and Deploy
- Node.js React web app - separate stages for Build and Deploy

Adding template for nodejs function app on linux, and modifying Express and React templates to have separate Build and Deploy stages.

---

design/pipeline-artifacts.md
design/pipeline-resources.md

I have added few clarifications to build resource spec and updated the pipeline artifacts spec regarding supporting `download` macro with the scenario - download all available artifacts to a specified path.

Ashokirla resources updates

---

templates/deploy-to-existing-kubernetes-cluster.properties.json

Corresponding AzDev PR: https://dev.azure.com/mseng/_git/AzureDevOps/pullrequest/466367

Change servicePort input to be a pickList

---

design/pipeline-resources.md
design/pipeline-triggers.md

Updated spec for ACR container resource.

Ashokirla acr update

---

templates/deploy-to-existing-kubernetes-cluster.yml

Complying changes with this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/10570

[k8s] Fetching namespace from endpoint

---

design/deployment.md
design/environment.md

Support for continueOnError, timeouts, variables etc and template references in deployment job

Introducing deployment job properties

---

templates/docker-build.properties.json
templates/docker-build.yml

Signed-off-by: Rajendra Kolli <rakol@microsoft.com>

Adding a Docker build only template

---

README.md
design/README.md
design/artifacts-in-pipelines.md

Provide clarity on where current documentation is to be found.

Direct users to docs for current documentation

---

design/environment.md

Macro proposal for review app resources in Environment
For more details about the review app feature refer to the spec: https://microsoftapc-my.sharepoint.com/:w:/g/personal/atulmal_microsoft_com/EbSJCOm_ni1Dsa1Fhv5KygkBam3JxXauHlB8GkdUmFR6YA?e=fexk2F
The spec has a sample pipeline yaml which builds and deploys an app to a K8s cluster for review app feature.

Added a macro proposal for review app resources in Environment

---

design/pipeline-resources.md
design/pipeline-triggers.md

Added specs for package resource support in resources and webhook based triggers.

Ashokirla patch 1

---

templates/xcode.yml

PR contains an update for "xcode.yml" with information about a new option in version selector (Related to issue [#12373 ](https://github.com/microsoft/azure-pipelines-tasks/issues/12373) from azure-pipelines-tasks).

[XcodeV5] Update task template

---

templates/ant.yml
templates/asp.net-core.yml
templates/docker-build.yml
templates/docker-container-functionapp.yml
templates/docker-container-to-acr.yml
templates/docker-container-to-aks.yml
templates/docker-container-webapp.yml
templates/empty.yml
templates/gcc.yml
templates/go.yml
templates/gradle.yml
templates/html.yml
templates/jekyll-container.yml
templates/maven.yml
templates/node.js-with-angular.yml
templates/node.js-with-grunt.yml
templates/node.js-with-gulp.yml
templates/node.js-with-react.yml
templates/node.js-with-vue.yml
templates/node.js-with-webpack.yml
templates/node.js.yml
templates/php.yml
templates/python-django.yml
templates/python-package.yml
templates/ruby.yml

These templates are used in Azure DevOps Server pipelines, which won't have access to the hosted pipelines. This adds mustache templates for the service to replace with an appropriate string.

replacing vmImage: 'ubuntu-latest' with {{ pool }}

---

templates/xcode.yml

PR contains an update for "xcode.yml" with information about a new option in the version selector (Related to issue #[13677](https://github.com/microsoft/azure-pipelines-tasks/issues/13677) from azure-pipelines-tasks).

Update comment in xcode template

---

design/pipeline-resources.md

I removed a typo which breaks code highlighting

Fixed code highlighting

---

design/pipeline-triggers.md

Just a correction of some copy-paste actions and a small typo.

Typo and other changes in pipeline-triggers.md

---

.github/autoAssignABTT.yml

Auto assign action - fixed token, label name

Auto assign action - fixed token, label name
